[package]
name = "breez-sdk-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.57", features = ["backtrace"] }
breez-sdk-core = { path = "../../libs/sdk-core"}
env_logger = "*"
hex = "*"
log = "*"
once_cell = "*"
rustyline = "10.0.0"
serde_json = "1.0"
tiny-bip39 = "*"
tokio = { version = "1", features = ["rt-multi-thread"] }