[package]
name = "breez-sdk-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "10.0.0"
tiny-bip39 = "*"
hex = "*"
breez-sdk-core = { path = "../../libs/sdk-core"}
serde_json = "1.0"
anyhow = { version = "1.0.57", features = ["backtrace"] }
env_logger = "*"
log = "*"